import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RootProvider } from "../component/rootProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const initData = async () => {
  const response = await fetch("http://localhost:3000/api/list");
  const usersData = await response.json();
  return usersData;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await initData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider data={data}>{children}</RootProvider>
      </body>
    </html>
  );
}
